# rule identifiers turned on by default to exclude from running
disabled_rules:
  - no_fallthrough_only
  - inclusive_language
  - compiler_protocol_init
  - unused_setter_value
  - todo
  - nesting
  - function_parameter_count
  - shorthand_operator
  - multiple_closures_with_trailing_closure
  - inert_defer
  - type_name
  - identifier_name
  - force_cast
  - force_try
   
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 6000
identifier_name:
  min_length: # only min_length
    warning: 1 # only warning
    error: 1 # only error
  max_length: 
    warning: 60 # only warning
    error: 100 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
  validates_start_with_lowercase: false
  allowed_symbols: "_"
type_body_length:
  - 800 # warning
  - 1600 # error
function_body_length:
  warning: 200
  error: 500
type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 100
  validates_start_with_lowercase: false
file_length:
  warning: 2000
  error: 5000
  ignore_comment_only_lines: true
cyclomatic_complexity:
  warning: 30
  error: 100
  ignores_case_statements: true
