name: SwiftLint on Changed Files

on: 
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  swiftlint:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install SwiftLint
      run: |
        brew install swiftlint

    - name: Lint Modified Swift Files
      run: |
        git fetch origin ${{ github.base_ref }}
        git diff --name-only origin/${{ github.base_ref }} | grep '\.swift$' | xargs swiftlint lint
