name: SwiftLint on Changed Files

on: push

jobs:
  swiftlint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # fetch all history so that we can get the proper list of changed files

    - name: Get changed files
      id: changes
      # Set outputs using the command.
      run: |
        echo "::set-output name=all::$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | xargs)"

    - name: Install SwiftLint
      run: brew install swiftlint

 #   - name: List all changed files
 #     id: files
 #     uses: jitterbit/get-changed-files@v1
 #     with:
 #       format: space-delimited

    - name: Run SwiftLint on changed files
      run: |
        # Extract changed files and filter for Swift files
        FILES="${{ steps.changes.outputs.all }}"
        SWIFT_FILES=$(echo "$FILES" | grep -E '\.(swift)$' | xargs)
        # Run SwiftLint on each changed Swift file
        # If no Swift files changed, skip the step
        if [ -z "$SWIFT_FILES" ]; then
          echo "No Swift files to lint."
        else
          echo "Linting changed Swift files..."
          swiftlint --config dydx/.swiftlint.yml --fix --format lint -- $SWIFT_FILES
        fi

    - name: Commit and push if needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Apply SwiftLint fixes" || true # Commit if there are changes; do nothing if there are none
        git push || echo "No changes to push"
